### ISSUE TITLE
setjy step seems frozen after almost 15 hours

### ISSUE THREAD

**Issue by IanHeywood** [idia-astro/pipelines#41]
I've killed it, if anyone wants to pick through the bones they're here (for now):

```
/ceph/pipelines/ianh/LADUMA_61/idia
```

Cheers.

**Comment by Kitchi** [comment]
We think this was an issue with the SLURM controller/cluster that seems to have gone away after various updates and fixes to the system. Basically 

(a) If CASA completes successfully it doesn't always report that to SLURM so SLURM keeps the job spinning until timeout

(b) More rarely, if there's a network interrupt to a CASA task while it's in the middle of an IO operation it can hang without crashing. We haven't managed to pin down exactly what causes this to happen, but as far as we are aware it doesn't happen very often and is not a major cause for concern.

I'm closing the issue for now.

**Comment by Jordatious** [comment]
To add to this, within our current version of the pipeline, the SLURM job that runs setjy basically always claims to fail, but actually doesn't, and so finishes the setjy job (unlike the behaviour above) and proceeds with the following jobs.
