### ISSUE TITLE
Need better parallactic angle coverage detection

### ISSUE THREAD

**Issue by Kitchi** [idia-astro/pipelines#44]
For short observations (few hours or less) with insufficient parallactic angle coverage, the `xy_yx_cal.py` step fails leading to a much lowered flux density scale and a worse phase calibration. 

This needs to be handled more intelligently by the scripts, disabling `xy_yx` calibration if parallactic angle coverage is under 30 degrees. This should be fairly straightforward to calculate from the source position and time of observations.

**Comment by Jordatious** [comment]
It would be good to expand this to also check the bandwidth for which you're solving. In either case, we should warn the user when they're trying to launch the pipeline, and disable `xy_yx`.

**Comment by Jordatious** [comment]
Fixed in 0d466b7066ba1bf76663b674febea90e8965428f
