### ISSUE TITLE
Error in plotcal script.

### ISSUE THREAD

**Issue by dentalfloss1** [idia-astro/pipelines#48]
plotcal script failed and produced an error:
```
2020-09-08 21:14:22,418 ERROR: Exception found in the pipeline of type <type 'exceptions.ValueError'>: total size of new array must be unchanged
2020-09-08 21:14:22,418 ERROR: Traceback (most recent call last):
  File "/idia/software/pipelines/master/processMeerKAT/crosscal_scripts/plotcal_spw.py", line 264, in main
    plotcal(plotstr, int(ff), spwdir, caldir, table_ext, title, outname)
  File "/idia/software/pipelines/master/processMeerKAT/crosscal_scripts/plotcal_spw.py", line 179, in plotcal
    ydatx = ydatx.reshape(fields.shape)
ValueError: total size of new array must be unchanged
```
Perhaps this is a CASA error? The rest of the run succeeded and seemed to produce good results. Attached is the only logfile that was not empty.

[plotcal_spw-117290_casa.txt](https://github.com/idia-astro/pipelines/files/5195790/plotcal_spw-117290_casa.txt)

**Comment by Kitchi** [comment]
Hey @dentalfloss1 thanks for letting us know. Can you point me to where the caltables are? I've seen this issue before and it should have been patched. But this might be because I haven't taken certain caltable configurations into account.

The rest of the pipeline run will be unaffected. Are you using the `dev` or `master` branch?

**Comment by dentalfloss1** [comment]
The root directory is /scratch2/users/sarahchastain/1599526861 with the caltables being in the subdirectories of the spws. 
I using: 'source /idia/software/pipelines/master/setup.sh' which I am expecting to be release 1.1  Is that correct?

**Comment by Kitchi** [comment]
Hi Sarah,

This has been fixed in the `dev` branch which can be found here - `/idia/software/pipelines/dev`. Please let us know if it doesn't work for any reason! Thanks for the report.
