### ISSUE TITLE
casa-6.5.0-modular.sif

### ISSUE THREAD

**Issue by manuparra** [idia-astro/pipelines#57]

**Comment by manuparra** [comment]
Hi, I wanted to ask if the definition file to build the SIF for singularity is available.  Would it be correct to use the generic CASA 6.5 container?

**Comment by Jordatious** [comment]
Hi @manuparra, no problems. I've added you as a reader to the repository we use that contains the recipe file.

**Comment by manuparra** [comment]
Hi @Jordatious could you give me access again to get the recipe? I couldn't get the file.

**Comment by Jordatious** [comment]
Hi @manuparra, that's strange. Did you accept the previous invite? I've sent another one now. Please let me know if that works.

**Comment by manuparra** [comment]
Thank you again! 
When I went to access it, github told me that it had expired :)

**Comment by Jordatious** [comment]
Hi @manuparra, no problems. I'm glad you're sorted now!
